version: "3.8"

name: chapter-sync
services:
  watch:
    image: dancardin/chapter-sync:latest
    build:
      context: .
    restart: always
    command: watch
    volumes:
      - "./:/chapter-sync"
      - "./data:/data"

  web:
    image: dancardin/chapter-sync:latest
    build:
      context: .
    restart: always
    command: web --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - "./:/chapter-sync"
      - "./data:/data"
