version: "3.8"

name: chapter-sync
services:
  watch:
    image: dancardin/chapter-sync:latest
    restart: always
    command: watch
    volumes:
      - "${PWD}/chapter_sync.sqlite:/chapter-sync/chapter_sync.sqlite"

  web:
    image: dancardin/chapter-sync:latest
    restart: always
    command: web --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - "${PWD}/chapter_sync.sqlite:/chapter-sync/chapter_sync.sqlite"
